apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240503030736.0.0+build.6aff574
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240503030736.0.0+build.6aff574
  releaseNotes: |
    Release v20240503030736.0.0+build.6aff574 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-02-05-2024-19-27-19-155143392/where-for-dinner-search-my-apps-bundle@sha256:81c13e12747e5540d53e5d53a2e0482418975de75ee87be11a72c91392663d0e
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

